{% set name = "OceansDB" %}
{% set version = "0.8.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 807f654a82c98ae733b24737d751d7bc0630121de9324218e8405397a362053c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - netcdf4 >=1.2.4
    - numpy >=1.14
    - scipy >=1.1
    - supportdata >=0.1.3

test:
  imports:
    - oceansdb
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/castelao/oceansdb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Package to subsample ocean climatologies and reference data.
  doc_url: https://oceansdb.readthedocs.io
  dev_url: https://github.com/castelao/oceansdb

extra:
  recipe-maintainers:
    - castelao
